4
KimGeorgy/Android-Mipt-Kotlin-2024-Kim-Georgy pull request #5
Opened 2024-03-06 20:25 UTC by KimGeorgy

2024-03-08 08:08 UTC, Ksalim01 requested changes

2024-03-08 08:08 UTC, Ksalim01 commented on 4.kt
> +fun findIntersection(a: Point, b: Point, c: Point, d: Point): Point? {
Заведи отдельный класс с двумя точками и назови Segment. В этом сегменте добавь этот метод, либо сделай дата класс и через экстеншен добавь метод isIntersected. Очень сложно читать такой код и очень легко ошибиться, когда пишешь такой код

2024-03-08 16:47 UTC, KimGeorgy commented on 4.kt
> +fun findIntersection(a: Point, b: Point, c: Point, d: Point): Point? {
сделал класс Segment

2024-03-31 07:41 UTC, Ksalim01 approved these changes

2024-03-31 07:41 UTC, merged